apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
  labels:
    app: ecommerce
type: Opaque
data:
  # Base64 encoded secrets (for Minikube testing)
  # These are dummy values for testing
  SPRING_DATASOURCE_USERNAME: c2E=  # "sa"
  SPRING_DATASOURCE_PASSWORD: ""   # empty
  JWT_SECRET: dGVzdC1qd3Qtc2VjcmV0LWZvci1taW5pa3ViZQ==  # "test-jwt-secret-for-minikube"
  ENCRYPTION_KEY: dGVzdC1lbmNyeXB0aW9uLWtleQ==  # "test-encryption-key"
